<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ArcadeGame extends Model
{
    use HasFactory;
    protected $table = 'arcade_game';
    public $timestamps = false;
    protected $fillable = [
      'genre',
      'engine',
      'title',
      'seo_url',
      'image',
      'code',
      'arcade_category_id',
      'featured',
      'views',
      'timestamp',
    ];
    static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($query) {
            $query->timestamp = Carbon::now();
        });
    }

    public function arcadeCategory(): BelongsTo
    {
        return $this->belongsTo(ArcadeCategory::class,'arcade_category_id','id');
    }
}
