<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class CartProduct extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $table = 'cart_product';
    protected $fillable = [
      'cart_id',
      'product_id',
      'quantity',
    ];
//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//        static::creating(function ($query) {
//            $query->timestamp = Carbon::now();
//        });
//    }


//  TODO: Relationship Start
    public function cart(): BelongsTo
    {
        return $this->belongsTo(Cart::class,'cart_id','id');
    }

    public function products()
    {
        return $this->belongsTo(Product::class,'product_id','id');
    }
//  TODO: Relationship End
}
