<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CreditsActivity extends Model
{
    use HasFactory;
    protected $table = 'credits_activity';
    public $timestamps = false;
    protected $fillable = [
        'user_id',
        'type',
        'description',
        'change',
        'credits_before',
        'credits_after',
        'timestamp',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($query) {
            $query->timestamp = Carbon::now();
        });
    }

}
